name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/registry-manager .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/registry-manager